version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    depends_on:
      - server

  server:
    build:
      context: ./server
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    expose:
      - 8000
    depends_on:
      - database

  database:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
  
  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 80:80     # 443 HTTPS
    depends_on:
      - client
      - server

volumes:
  mysql-data:
