version: '3.8'
services:
  client:
    build:
      context: ./client
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    depends_on:
      - database

  database:
    image: mysql:latest
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bowleg.historic.TORI
      MYSQL_DATABASE: exploration
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1

volumes:
  mysql-data: