services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bowleg.historic.TORI
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
